name: Build and Test with Maven

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Maven dependencies
      uses: actions/cache@v3   # Updated version of actions/cache
      with:
        path: ~/.m2/repository   # Path to Maven local repository cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}   # Key for cache
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run Tests with Maven
      run: mvn test

