name: Build and Test with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - name: Change to correct directory
      run: cd sit333_task9_1p/task9_1P/springws

    - name: Set up JDK 11 (Oracle)
      uses: actions/setup-java@v2
      with:
        java-version: 17-ea
        distribution: adopt 

    - name: Build with Maven
      run: mvn clean install -DskipTests
      working-directory: sit333_task9_1p/task9_1P/springws

    - name: Run Tests with Maven
      run: mvn test
      working-directory: sit333_task9_1p/task9_1P/springws

